package org.shark.mentor.mcp.application.service.llm;

import reactor.core.publisher.Flux;

public interface LlmService {

    /**
     * Generate a response to the given question using only the supplied context.
     * Implementations must not infer or add information that is not present in
     * the context.
     *
     * @param question the user's original question
     * @param context  additional information retrieved from the MCP server
     * @return the model generated answer
     */
    String generate(String question, String context);

    /**
     * Generate a streaming response to the given question using only the supplied context.
     * This method returns a Flux that emits tokens as they are generated by the LLM.
     * Implementations must not infer or add information that is not present in
     * the context.
     *
     * @param question the user's original question
     * @param context  additional information retrieved from the MCP server
     * @return a Flux of tokens that make up the model generated answer
     */
    default Flux<String> generateStream(String question, String context) {
        // Default implementation for backward compatibility
        // Emits the complete response as a single token
        return Flux.just(generate(question, context));
    }
}
