server:
  port: 8083
mcp:
  server:
    port: 3000
    host: localhost
  servers:
    - id: melian-local
      name: "Melian MCP Server (Local)"
      description: "Local MELIAN - M\xF3dulo de Embedding y L\xF3gica Inteligente para Acceso Natural. Provides movie data from TMDB, SQL databases, and MongoDB."
      url: "stdio://java -jar ../target/melian-*.jar"
    - id: github-mcp
      name: "GitHub MCP Server"
      description: "Provides access to GitHub repositories, issues, and pull requests"
      url: "stdio://npx @modelcontextprotocol/server-github"
    - id: filesystem-mcp
      name: "File System MCP Server"
      description: "Provides secure access to local file system operations"
      url: "stdio://npx @modelcontextprotocol/server-filesystem"
    - id: brave-search-mcp
      name: "Brave Search MCP Server"
      description: "Provides web search capabilities through Brave Search API"
      url: "stdio://npx @modelcontextprotocol/server-brave-search"
    - id: sqlite-mcp
      name: "SQLite MCP Server"
      description: "Provides database query capabilities for SQLite databases"
      url: "stdio://npx @modelcontextprotocol/server-sqlite"

spring:
  application:
    name: mcp-client-backend
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
logging:
  level:
    org.shark.mentor.mcp: INFO
    org.springframework.web: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
